### ISSUE TITLE
While building (react-native run-android) undefined reference of WritabaleArray caused error.

### ISSUE THREAD

**Issue by astriskit** [himelbrand/react-native-ble-peripheral#1]
https://github.com/himelbrand/react-native-ble-peripheral/blob/c03f7856421a19b5f15fd4d2d7590710ec829bc0/android/src/main/java/com/himelbrand/ble/peripheral/RNBLEModule.java#L146

I tried -
"import com.facebook.react.bridge.WritableArray;"

And I was able to run at-least. See, if this is alright.

**Comment by himelbrand** [comment]
fixed, thank you.
next time you are welcome to make a pull request
