### ISSUE TITLE
Does not build.

### ISSUE THREAD

**Issue by astriskit** [himelbrand/react-native-ble-peripheral#2]
Hi. Thanks for writing this library.
While building error indicating following killed it - @Override( lineno- 139 in RNBLEModule.java ) - No method found to override.
I tried to comment it out. And build was successful. 
Please see if this is right!

**Comment by himelbrand** [comment]
Hi thank you for opening this issue,
I'll check this issue, you mean you commented out the @override , right?

**Comment by astriskit** [comment]
@himelbrand Sorry, I couldn't reply earlier. And yes, I commented that.

**Comment by bassment** [comment]
Hi @himelbrand 

1) True, build is failing, so I had to comment out _**onCharacteristicWriteRequest**_ method, luckily I don't need it anyway :)
2) After that I have another problem about _**android:minSdkVersion**_ which is set to **23** in _**exploaded_arr**_ in your dependency lib. I had to override it by setting tools:overrideLibrary="com.himelbrand.ble.peripheral" in my AndroidManifest.
3) Then everything is building correctly but I encounter another problem when actually writing this code in react native file:

```
async componentWillMount() {
    try {
      await BLEPeripheral.addService('649d8b56-b607-439a-bb83-7e0d00838cf1', false);
      await BLEPeripheral.addCharacteristicToService(
        '649d8b56-b607-439a-bb83-7e0d00838cf1',
        '9dd72f92-f0cb-11e7-8c3f-9a214cf093ae',
        16 | 1, 8,
      );
      const result = await BLEPeripheral.start();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  }
```

And the **error** is:
```
Attempt to invoke virtual method 
'boolean android.bluetooth.BluetoothGattServer.addService(android.bluetooth.BluetoothGattService)'
on a null object reference
start
    RNBLEModule.java:173
invoke
    Method.java
invoke
    Method.java:372
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818

```

And this is the code which is failing in RNBLEModule.java file:
```
@ReactMethod
    public void start(final Promise promise){
        mBluetoothManager = (BluetoothManager) context.getSystemService(Context.BLUETOOTH_SERVICE);
        mBluetoothAdapter = mBluetoothManager.getAdapter();
        // Ensures Bluetooth is available on the device and it is enabled. If not,
// displays a dialog requesting user permission to enable Bluetooth.

        mBluetoothDevices = new HashSet<>();
        mGattServer = mBluetoothManager.openGattServer(reactContext, mGattServerCallback);
        for (BluetoothGattService service : this.servicesMap.values()) {
            mGattServer.addService(service);    //  mGattServer HERE IS NULL!
        }
       ........
```

Could you please help me with this? BTW, awesome work and repo, thanks for writing it. I'm not that good with Java myself so I appreciate if you could help ;)

**Comment by himelbrand** [comment]
@bassment thank you for the info,
and thank you for the kind words.
about this error you're having, 
it'll be better if I could see your initialization of the module (in react native code)
also I didn't understand what is the problem you are having with android:minSdkVersion when it is set to 23 , are you using a lower min-sdk version?
and also if you can try building with the new version i'm publishing right now version - 1.1.8
let me know if  there is any change

**Comment by bassment** [comment]
@himelbrand thanks for fast reply!

I tried new version from you and it has this error: 
```
node_modules/react-native-ble-peripheral/android/src/main/java/com/himelbrand/ble/peripheral/RNBLEModule.java:147: error: cannot find symbol:

WritabaleArray data = Arguments.createArray();
            ^
  symbol: class WritabaleArray
Note: node_modules/react-native-ble-peripheral/android/src/main/java/com/himelbrand/ble/peripheral/RNBLEModule.java uses or overrides a deprecated API.
```
Looks like WritabaleArray is deprecated API.

What do you mean about initialization of the module (in react native code)? If you mean is it linked correctly, than yes. I typed react-native link. And then checked if module is initialized everywhere. Looks ok. Maybe you need some of my files? I could show you any,  just name the file. 

And nevermind about the min version.

**Comment by bassment** [comment]
Ok, I'll get it now :) 

Because I was overriding version I couldn't get it to work since I was running it on 22 sdk device. And the minimum required version is 23. I tried it on 27 sdk and it works fine. Thanks for the cool lib!

@himelbrand But you still need to fix WritabaleArray ;)

**Comment by himelbrand** [comment]
@bassment yes, that is the reason this is the minimum version
about the writable array, can you please open a new issue?
please add the following info:
react native version
your OS when trying to build

I'm closing this issue since it's main topic is fixed
