### ISSUE TITLE
Couldn't start the advertising after adding the service and characteristics.

### ISSUE THREAD

**Issue by astriskit** [himelbrand/react-native-ble-peripheral#3]
I tried to start advertising without adding service and characteristics. And I could see the beacon advertising with the device name as name. But couldn't add my services. The function fails with - Error: Advertising onStartFailure: 1
For reference - I added service and characteristics like following - 
```
BlePeripheral.addService('76c14520-9b41-4e13-a229-e29059c00e47', false)
BlePeripheral.addCharacteristicToService('76c14520-9b41-4e13-a229-e29059c00e47', '76c11234-9b41-4e13-a229-e29059c00e47', 16|1, 8 )
```

**Comment by himelbrand** [comment]
Hi,
you need to add services and characteristics before you start advertising.
I hope that answers your issue

**Comment by mtumiati** [comment]
I nave the esame problem. I ad the service and the caratteristica. After that, when I start the advertising, I get the error.
