### ISSUE TITLE
Typo preventing from compiling

### ISSUE THREAD

**Issue by alwex** [himelbrand/react-native-ble-peripheral#4]
should be `WritableArray`

https://github.com/himelbrand/react-native-ble-peripheral/blob/d26a1a125223acd56e1701cdc9af80dac7c6cdc2/android/src/main/java/com/himelbrand/ble/peripheral/RNBLEModule.java#L147

**Comment by himelbrand** [comment]
@alwex thank you for opening this issue.
I fixed the typo, so i'm closing this issue.
for future case just so you know, you are more than welcome to open a PR with a fix
