### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by himelbrand** [himelbrand/react-native-ble-peripheral#5]
## help wanted to implement support for ios.
for all functionality that exist and possible to add more features,  
in case of new features if it's possible I'll implement for android.

thank you all

**Comment by EskelCz** [comment]
I really need this so I guess I'll try to learn how to write it.
Any opinion whether it should be in Objective C or Swift? Because I'd rather learn Swift. :)

**Comment by himelbrand** [comment]
@EskelCz thanks for the help,
and about the language, I believe it can be done using both, just check the ios BLE API to verify

**Comment by EskelCz** [comment]
Seem like swift will be ok, basic scaffolding is working fine.
One question, why is "isAdvertising" a promise resolution? Even simple property return cannot be done synchronously?

**Comment by EskelCz** [comment]
@SashaStojanovic I’m working on it, I’ll probably have it done before the end of the month.

**Comment by SashaStojanovic** [comment]
@EskelCz alright, awesome!! On this master branch? So I can install this via NPM and then implement android for now and IOS can follow later?

**Comment by EskelCz** [comment]
@SashaStojanovic That’s the plan. :) If eveything goes well.

**Comment by SashaStojanovic** [comment]
@EskelCz I have created my own library in my own project and basically extracted your code out as I needed to install a working version of android and IOS into my project. I've got this mostly working however, I cannot seem to get the callbacks working on didReceiveReadRequest and didReceiveWriteRequests. I am able to read the characteristics from another device, but the callbacks are just never hit, did you experience this at all?

This makes it impossible for me to know when a characteristic is written to.

**Comment by SashaStojanovic** [comment]
@himelbrand @EskelCz are you guys able to merge here so I can try out the ios version please

**Comment by EskelCz** [comment]
@SashaStojanovic I haven’t tested anything with characteristics, sorry. It would be great if you would figure it out and open a PR. You can fork my fork and make changes there.
Also this doesnt need to be merged right away, you can use PR address in package json, or a git url.

**Comment by anshzinc** [comment]
@EskelCz @SashaStojanovic 
I'm trying to get your pull request to work, I'm getting following exception:

> Exception 'addCharacteristicToService:permissions:properties:data: is not a recognized Objective-C method.' was thrown while invoking addCharacteristicToService on target BLEPeripheral with params (
>     "85E12C9B-6EB5-4623-9760-FC6F98834402",
>     "CA8181BD-F10D-4F67-942B-C62042B6C4FD",
>     17,
>     8
> )

I'm new to Swift/ios. I've tried with Swift 5 and 4 (Build setting). Any ideas?

**Comment by SashaStojanovic** [comment]
@anshzinc I also had the same issue when trying to get it all to work. I opened up xCode and changed the interface that described addCharacteristicToService to include the UUID that is missing.

**Comment by SashaStojanovic** [comment]
@anshzinc the addCharacteristicToService is not actually working though. The code runs but is never applied. The service characteristic count is always 0 even after the characteristics?.append(characteristic) is called

**Comment by anshzinc** [comment]
@SashaStojanovic Thanks, I'll figure out adding the missing UUID. 

Secondly if the addCharacteristicToService is not working how are you able to read characteristics from another device?

**Comment by SashaStojanovic** [comment]
@anshzinc I did not fork the repo or anything, but what I did was, I created a librray and extracted the IOS logic into it to see if I could get it to work. I changed the way the addService and addCharacteristicToService as I just couldn't get the characteristics to stick with that Dictionary.

Using the below, I managed to get it working (singular service only) and advertising the characteristics, but ...... the callbacks for didReceiveWriteRequest and didReceiveReadRequest are never hit which is where I am currently stuck ... strange because I can read the data in the characteristics, but "didReceiveReadRequest" is never fired.

`import Foundation
import CoreBluetooth

@objc(RNAdvertiseBle)
class RNAdvertiseBle: RCTEventEmitter, CBPeripheralManagerDelegate {
    
    var advertising: Bool = false
    var hasListeners: Bool = false
    var service: CBMutableService!
    var characteristics: [CBMutableCharacteristic] = []
    
    var manager: CBPeripheralManager!
    
    //promise results
    var startPromiseResolve: RCTPromiseResolveBlock?
    var startPromiseReject: RCTPromiseRejectBlock?
    
    override init() {
        super.init()
        manager = CBPeripheralManager(delegate: self, queue: nil, options: nil)
    }
    
    //public function to add a service into the stack
    @objc(addService:primary:)
    func addService(_ uuid: String, primary: Bool) {
        let serviceUUID = CBUUID(string: uuid)
        service = CBMutableService(type: serviceUUID, primary: primary)
    }
    
    //public function to add a characteristic into an existing service
    @objc(addCharacteristicToService:uuid:data:permissions:properties:)
    func addCharacteristicToService(_ serviceUUID: String, uuid: String, data: String, permissions: UInt, properties: UInt) {
        let characteristicUUID = CBUUID(string: uuid)
        let propertyValue = CBCharacteristicProperties(rawValue: properties)
        let permissionValue = CBAttributePermissions(rawValue: permissions)
        
        let byteData: Data = data.data(using: .utf8)!
        characteristics.append(CBMutableCharacteristic( type: characteristicUUID, properties: propertyValue, value: byteData.count != 0 ? byteData : nil , permissions: permissionValue))
        print("Added characteristic \(uuid) to service")
    }
    
    @objc func start(_ resolve: @escaping RCTPromiseResolveBlock, rejecter reject: @escaping RCTPromiseRejectBlock) {
        if (manager.state != .poweredOn) {
            return;
        }
        
        service.characteristics = characteristics
        manager.add(service)
        
        startPromiseResolve = resolve
        startPromiseReject = reject
        
        let advertisementData = [
            CBAdvertisementDataLocalNameKey: "",
            CBAdvertisementDataServiceUUIDsKey: [service.uuid]
            ] as [String : Any]
        manager.startAdvertising(advertisementData)
    }
    
    @objc func stop() {
        manager.stopAdvertising()
        advertising = false
    }

    //Advertising started
    func peripheralManagerDidStartAdvertising(_ peripheral: CBPeripheralManager, error: Error?) {
        if let error = error {
            advertising = false
            startPromiseReject!("AD_ERR", "advertising failed", error)
            return
        }
        advertising = true
        startPromiseResolve!(advertising)
        print("advertising succeeded!")
    }
    
    func peripheralManager(peripheral: CBPeripheralManager, didReceiveReadRequest request: CBATTRequest)
    {
        request.value = request.characteristic.value
        manager.respond(to: request, withResult: .success)
    }
    
    //Callback for when characteristic is written to
    func peripheralManager(peripheral: CBPeripheralManager, didReceiveWriteRequests requests: [CBATTRequest])
    {
        for request in requests
        {
            let characteristic = request.characteristic as! CBMutableCharacteristic
            characteristic.value = request.value
            
            //Send callback back to js
            sendEvent(withName: "OnWriteReceived", body: "Write received")
        }
        manager.respond(to: requests[0], withResult: .success)
    }
    
    @objc func isAdvertising(_ resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        resolve(advertising)
    }
    
    func peripheralManagerDidUpdateState(_ peripheral: CBPeripheralManager) {
        var state: Any
        if #available(iOS 10.0, *) {
            state = peripheral.state.description
        } else {
            state = peripheral.state
        }
        print("peripheralManagerDidUpdateState called")
    }
    
    @objc override func supportedEvents() -> [String]! { return ["onWarning"] }
    override func startObserving() { hasListeners = true }
    override func stopObserving() { hasListeners = false }
    @objc override static func requiresMainQueueSetup() -> Bool { return false }
    
   
}

@available(iOS 10.0, *)
extension CBManagerState: CustomStringConvertible {
    public var description: String {
        switch self {
        case .poweredOff: return ".poweredOff"
        case .poweredOn: return ".poweredOn"
        case .resetting: return ".resetting"
        case .unauthorized: return ".unauthorized"
        case .unknown: return ".unknown"
        case .unsupported: return ".unsupported"
        }
    }
}`

**Comment by SashaStojanovic** [comment]
@anshzinc I also just changed the position of the "data" parameter in addCharacteristicToService so that it was the same as the android version

**Comment by anshzinc** [comment]
@SashaStojanovic Unfortunately I'm not familiar with Swift as well. Thanks for the code though, I'm going to be digging into it. Currently I'm still running into issues with addCharacteristicToService change.

**Comment by SashaStojanovic** [comment]
@anshzinc if you use my addCharacteristicToService function and then you use this in the interface , it should work.

> RCT_EXTERN_METHOD(
                  addCharacteristicToService: (NSString *)serviceUUID
                  uuid:                       (NSString *)uuid
                  data:                       (NSString *)data
                  permissions:                (NSInteger *)permissions
                  properties:                 (NSInteger *)properties
                  )

**Comment by EskelCz** [comment]
For the reference (I found this in my test project) this was my test code for adding characteristics:
`BLEPeripheral.addCharacteristicToService('76c14520-9b41-4e13-a229-e29059c00e47', '76c11234-9b41-4e13-a229-e29059c00e47', 16 | 1, 8)`

I haven't seen errors but haven't tested reading the characteristics.
It would be best to add tests for all these, but I'm not familiar with unit test environment for ios.

**Comment by himelbrand** [comment]
@EskelCz I approved your PR,
Thank you.
sorry for taking so long to do so

**Comment by kendhia** [comment]
@EskelCz  is there a chance you update the doc on how did it work for you ? I'm getting an 
`TypeError: Cannot read property 'startSharedAdvertisingBeaconWithString' of undefined
`
While debugging, I found that `NativeModules.BeaconBroadcast` is returning an undefined obj.
